# Generated by Django 6.0.2 on 2026-07-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PeriodicDefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('periodic_id', models.CharField(blank=True, default='', max_length=200)),
                ('defer_at', models.DateTimeField(help_text='The scheduled slot this defer covers, not when it ran.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('task_name', 'periodic_id', 'defer_at'), name='unique_periodic_defer_slot'
                    )
                ],
            },
        ),
    ]
